# render.yaml

services:
  - name: todo-list-backend
    env: node
    startCommand: node index.js
    healthCheckPath: /
    envVars:
      - key: PORT
        value: "3000"  # Adjust port as needed
      - key: MYSQL_ADDON_HOST
        fromDatabase:
          name: bippeazoui0cugcsxdd3-mysql.services.clever-cloud.com    # Replace with your Clever Cloud MySQL database name
          property: hostname
      - key: MYSQL_ADDON_DB
        fromDatabase:
          name: bippeazoui0cugcsxdd # Replace with your Clever Cloud MySQL database name
          property: name
      - key: MYSQL_ADDON_USER
        fromDatabase:
          name: uehnjdy4m4lcnubp  # Replace with your Clever Cloud MySQL database name
          property: username
      - key: MYSQL_ADDON_PASSWORD
        fromDatabase:
          name: toU9B1tQCeY1WIU66F6c  # Replace with your Clever Cloud MySQL database name
          property: password
